import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@carbon/styles/css/styles.css";
import GlobalHeader from "@/components/Header";
import ClientProviders from "@/providers/client-providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <ClientProviders>
          <GlobalHeader />
          <main>{children}</main>
        </ClientProviders>
      </body>
    </html>
  );
}
