import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@carbon/styles/css/styles.css";

import GlobalHeader from "@/components/Header";
import I18nProvider from "@/providers/I18nProvider"; // Import provider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en"> {/* Use 'en' as default, language will be set inside provider */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <I18nProvider> {/* Handles language selection */}
          <GlobalHeader />
          <main>{children}</main>
        </I18nProvider>
      </body>
    </html>
  );
}
